# fly.toml app configuration file generated for maid on 2024-08-19T11:39:05+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'maid'
primary_region = 'ams'
swap_size_mb = 512

[build]
  [build.args]
    GO_VERSION = '1.21.3'

[env]
  PORT = '4664'

[http_service]
  internal_port = 4664
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

#[[mounts]]
#  source = 'test'
#  destination = '/data'
